### ISSUE TITLE
自动打标签报错

### ISSUE THREAD

**Issue by 12356abs** [yuchen02/AutoLabelImg#1]
![222](https://user-images.githubusercontent.com/78146399/222914766-fdbb036a-8463-4d7c-8ecc-f2b479d6fa7f.PNG)
auto_labelImg的时候报错

**Comment by yuchen02** [comment]
应该是你的电脑没有GPU,或者CUDA没装，也可能是CUDA版本不匹配，建议安装torch-gpu的版本

**Comment by 12356abs** [comment]
谢谢大佬，
解决了是cuda版本错误，但现在说我卷积通道出错
![3214](https://user-images.githubusercontent.com/78146399/223366457-c3ee5ca1-77ad-41ef-8a35-90391fda2f83.PNG)

**Comment by yuchen02** [comment]
⚠️暂不支持yolov5x6.pt等以6结尾的模型

**Comment by 12356abs** [comment]
重新建了虚拟环境解决了，但现在出现了这个问题
![捕获](https://user-images.githubusercontent.com/78146399/223433739-0602ba99-a828-4a2c-93e1-d952196d7d84.PNG)
